CREATE TABLE DEPARTAMENTO (
	IDDEPARTAMENTO NUMBER,
	NOMBRE VARCHAR2(50),
	PRIMARY KEY(IDDEPARTAMENTO));

ALTER TABLE empleado ADD ( IDDEPARTAMENTO NUMBER);

ALTER TABLE empleado 
ADD FOREIGN KEY (idEmpleado) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO);


INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOMBRE) VALUES (1, 'Contabilidad');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOMBRE) VALUES (2, 'Recursos Humanos');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOMBRE) VALUES (3, 'Aplicaciones');

ALTER TABLE empleado
	ADD ( GENERO VARCHAR2(1),
	 	FECHANACIMIENTO DATE);
	
ALTER TABLE empleado_has_planilla
	ADD ( SUELDONETO	NUMBER);	
		
UPDATE empleado SET GENERO='M', IDDEPARTAMENTO=1, FECHANACIMIENTO=TO_DATE('15/10/1999','DD/MM/YYYY') WHERE IDEMPLEADO=1;
UPDATE empleado SET GENERO='M', IDDEPARTAMENTO=1, FECHANACIMIENTO=TO_DATE('01/01/1989','DD/MM/YYYY') WHERE IDEMPLEADO=2;
UPDATE empleado SET GENERO='M', IDDEPARTAMENTO=3, FECHANACIMIENTO=TO_DATE('05/05/2000','DD/MM/YYYY') WHERE IDEMPLEADO=3;



Insert into EMPLEADO (IDEMPLEADO,PNOMBRE,SNOMBRE,PAPELLIDO,DIRECCION,TELEFONO,CELULAR,INCREMENTOSUELDO,IDEMPLEADOJEFE, GENERO, FECHANACIMIENTO) values ('4','KARLA','MEJIA','BUSTAMANTE','COM','32','23','0','2','F',TO_DATE('01/01/2001','DD/MM/YYYY'));


INSERT INTO cargo_empleado (idcargo, idempleado, fechaNombramiento)
VALUES (1,2, SYSDATE);

INSERT INTO cargo_empleado (idcargo, idempleado, fechaNombramiento)
VALUES (1,3, SYSDATE);



INSERT INTO PLANILLA (IDPLANILLA, FECHAEFECTIVA, FECHAINICIO, FECHAFIN)
VALUES (1, TO_DATE('30/01/2019','DD/MM/YYYY'), TO_DATE('01/01/2019','DD/MM/YYYY'), TO_DATE('30/01/2019','DD/MM/YYYY'));

INSERT INTO PLANILLA (IDPLANILLA, FECHAEFECTIVA, FECHAINICIO, FECHAFIN)
VALUES (2, TO_DATE('28/02/2019','DD/MM/YYYY'), TO_DATE('01/02/2019','DD/MM/YYYY'), TO_DATE('28/02/2019','DD/MM/YYYY'));

INSERT INTO PLANILLA (IDPLANILLA, FECHAEFECTIVA, FECHAINICIO, FECHAFIN)
VALUES (3, TO_DATE('30/03/2019','DD/MM/YYYY'), TO_DATE('01/03/2019','DD/MM/YYYY'), TO_DATE('30/03/2019','DD/MM/YYYY'));



INSERT INTO EMPLEADO_HAS_PLANILLA (EMPLEADO_IDEMPLEADO, PLANILLA_IDPLANILLA,SUELDONETO)  VALUES (1, 1, 10000);
INSERT INTO EMPLEADO_HAS_PLANILLA (EMPLEADO_IDEMPLEADO, PLANILLA_IDPLANILLA,SUELDONETO)  VALUES (1, 2, 10000);
INSERT INTO EMPLEADO_HAS_PLANILLA (EMPLEADO_IDEMPLEADO, PLANILLA_IDPLANILLA,SUELDONETO)  VALUES (1, 3, 10000);
INSERT INTO EMPLEADO_HAS_PLANILLA (EMPLEADO_IDEMPLEADO, PLANILLA_IDPLANILLA,SUELDONETO)  VALUES (2, 3, 11000);
INSERT INTO EMPLEADO_HAS_PLANILLA (EMPLEADO_IDEMPLEADO, PLANILLA_IDPLANILLA,SUELDONETO)  VALUES (3, 3, 12000);


