Insert into CARGO (IDCARGO,NOMBRE,SUELDOBASE) values ('1','Instructor','10000');
Insert into CARGO (IDCARGO,NOMBRE,SUELDOBASE) values ('2','Supervisor','20000');
Insert into CARGO (IDCARGO,NOMBRE,SUELDOBASE) values ('3','Jefatura','30000');
Insert into CARGO (IDCARGO,NOMBRE,SUELDOBASE) values ('4','Gerente','40000');


Insert into EMPLEADO (IDEMPLEADO,PNOMBRE,SNOMBRE,PAPELLIDO,DIRECCION,TELEFONO,CELULAR,INCREMENTOSUELDO,IDEMPLEADOJEFE) values ('1','PEDRO','JOSE','MEJIA','TGU','2222','232','0',null);
Insert into EMPLEADO (IDEMPLEADO,PNOMBRE,SNOMBRE,PAPELLIDO,DIRECCION,TELEFONO,CELULAR,INCREMENTOSUELDO,IDEMPLEADOJEFE) values ('2','JUAN','JOSE','AGUILAR','TGU','324','23','0','1');
Insert into EMPLEADO (IDEMPLEADO,PNOMBRE,SNOMBRE,PAPELLIDO,DIRECCION,TELEFONO,CELULAR,INCREMENTOSUELDO,IDEMPLEADOJEFE) values ('3','LUIS','ANTONIO','RAMIREZ','COM','32','23','0','2');



Insert into CARGO_EMPLEADO (IDCARGO,IDEMPLEADO,FECHANOMBRAMIENTO) values ('1','1',to_date('01/02/22','DD/MM/RR'));
Insert into CARGO_EMPLEADO (IDCARGO,IDEMPLEADO,FECHANOMBRAMIENTO) values ('2','1',to_date('15/07/22','DD/MM/RR'));
Insert into CARGO_EMPLEADO (IDCARGO,IDEMPLEADO,FECHANOMBRAMIENTO) values ('3','1',to_date('08/02/23','DD/MM/RR'));
